### ISSUE TITLE
Typo in template-functions.php

### ISSUE THREAD

**Issue by Mates-K1** [sbillard/ZenPhoto20-DEV#11]
<button id="submitbutton" class="button buttons **policyBurron** <?php echo $buttonClass; ?>" style="display:none;"<?php echo $buttonExtra; ?>>
(line 4345)

**Comment by sbillard** [comment]
Thanks. I think the new release is about ready. Any translation updates? (I've done the mechanical translation  update now, it is in the DEV_8 build which I am creating right now.

**Comment by Mates-K1** [comment]
Ok, thanks for notice. I work on it. I will send you it in about 12 hours.
