### ISSUE TITLE
Contact submit and register submit buttons are missing

### ISSUE THREAD

**Issue by Elinth** [sbillard/ZenPhoto20-DEV#12]
Hi Stephen,

On ZenPhoto20 version 1.6.2.08.DEV_12-DEBUG_404_OBJECTS the submit buttons are missing in the contact and registration page.

Cheers

Ewoud

**Comment by Elinth** [comment]
They disappear after the change in template-functions.php

**Comment by sbillard** [comment]
I will look into this. But also I notice you are still debugging the OBJECTS stuff. You should turn that off now.

**Comment by Elinth** [comment]
How do I turn this debugging off?

**Comment by sbillard** [comment]
Go to the options of the "debug" plugin and un-check it. Also you can mark the release the release "released" with the mark release button on the overview page. You should do both.

**Comment by Elinth** [comment]
Hi Stephen. 
I have no "mark release button" on the overview page.

**Comment by sbillard** [comment]
enable the debug plugin
