### ISSUE TITLE
 Search shows erratic behavior and no results on image description

### ISSUE THREAD

**Issue by Elinth** [sbillard/ZenPhoto20-DEV#13]
Hi Stephen,
The search functionality shows no results at all when I conduct a search on image description. While the text is on the page and searchable in the MYSQL.  Initial thought was that server cashing created the error. After a lot of communication with my host I found out that server or page cashing is not enabled on my server. They point me towards Zenphoto20.  See below comment from my host:

_We do not provide any server-side caching that is on by default and is applied on all sites. What my colleague was referring to is that we do offer caching support for CMSes if they have such options or for plugins that add such functionality. So the gist of it is that we do not force caching by default but we allow it should your site have support for it. If you have not enabled any such options in ZenPhoto we can confirm that there would be no caching active on the site. Feel free to reopen this ticket in case you have more questions or you need further assistance._

**Comment by sbillard** [comment]
I am out of town at the moment. I cannot reproduce this on my sites. But the problem with the description field not being checked would clause this. There is no way that Zenphoto20 Could cause what I observed. On Jun 14, 2018 9:56 AM, Elinth <notifications@github.com> wrote:Hi Stephen,
The search functionality shows no results at all when I conduct a search on image description. While the text is on the page and searchable in the MYSQL.  Initial thought was that server cashing created the error. After a lot of communication with my host I found out that server or page cashing is not enabled on my server. They point me towards Zenphoto20.  See below comment from my host:
We do not provide any server-side caching that is on by default and is applied on all sites. What my colleague was referring to is that we do offer caching support for CMSes if they have such options or for plugins that add such functionality. So the gist of it is that we do not force caching by default but we allow it should your site have support for it. If you have not enabled any such options in ZenPhoto we can confirm that there would be no caching active on the site. Feel free to reopen this ticket in case you have more questions or you need further assistance.

**Comment by sbillard** [comment]
I think this was closed a while back on the main repository.
