### ISSUE TITLE
Contact me

### ISSUE THREAD

**Issue by By-oussef** [sbillard/ZenPhoto20-DEV#18]
Hello, @sbillard I am Youssef the person who proposed to you changed name to zenphotographics and not to use zenphto20 because there was a confusion with zenphoto (in July 2018) but I was absent because I was gone on vacation . and you have created netphotographics. Today I come back with ideas for netphotographics and I want to contribute even more for this project, I can take care of updating to the latest version phpbb moreover I have competence in French and Spanish. I would like to redesign the netphotgraphics site, create language subdomains for the site ... Could you send me the username and password of the netphotographics server.
Could you contact me on email: youssef.elmourabit7@gmail.com

Thank you and happy to contribute with you on this project.

**Comment by sbillard** [comment]
The netPhotoGraphics server is the same as the one I use for my other sites, so it is not possible to give you server access. But please do propose the changes to the site. There is a repository for the site at https://github.com/ZenPhoto20/Website which you can clone and work with. When we have agreed to a change I can do the necessary uploading. 

I have not tried to keep the phpbb up to the latest version as there seems no need. The forum is little used and to date the phpbb changes have not seemed relevant. If you do notice something that suggest we should upgrade please create a ticket.

**Comment by By-oussef** [comment]
I understand can you give me access as an administrator to the phpbb forum of netphotographics. I want to make changes, make the moderator and some admin spots. Thank You for your collaboration.

**Comment by sbillard** [comment]
You should now be an administrator.

**Comment by By-oussef** [comment]
Thanks @sbillard  I just logged in and saw that gzip was not enabled. I think it must be activated to increase the speed of the site.

**Comment by sbillard** [comment]
The . htaccess file does enable "Deflate" I presume that is what you mean.
