### ISSUE TITLE
Add Web Builder Framework to NPG

### ISSUE THREAD

**Issue by By-oussef** [sbillard/ZenPhoto20-DEV#19]
Hi @sbillard  I think that NPG must now evolve to a simpler use and editing directly in the theme without changing the source code but directly from the inetrface. I think we can use a site builder

https://github.com/givanz/VvvebJs
Demo : http://www.vvveb.com/vvvebjs/editor.html

https://wordpress.org/gutenberg/
for example wordpress uses this thanks to Gutenberg.

**Comment by sbillard** [comment]
Sounds good. I look forward to your implementation.
