### ISSUE TITLE
Install NPG from a single file to download

### ISSUE THREAD

**Issue by By-oussef** [sbillard/ZenPhoto20-DEV#20]
you can simplify the NPG installation process by installing only a php file that will download the netphotographics folders and files and extract them. Then, users no longer need to install winrar or other extraction software because all will be on the server.

Like this : https://piwigo.org/doc/doku.php?id=user_documentation:learn:install:netinstall

**Comment by sbillard** [comment]
I am confused by this request. What about the netPhotoGraphics install options do you not understand?

**Comment by ghost** [comment]
Thanks @sbillard  for your answer, we made it not for me but more for users who do not want to completely install the script and then unzip and send all the script via ftp it takes time. Imagine a person who uses a limited 3g network loses a lot of bandpassante. Conversely if it downloads only 1 single file that must be 10ko maximum. The user transfers 1 single file and does not waste time.
Waiting for your reply.

**Comment by sbillard** [comment]
I do not think a user like you describe exists. Such a user will not look past the offerings of his hosting service. Aside from that, there are security issues with hosting an executable file. Unzipping or other extraction will always be needed, as will install instructions. Which are part of the container.
