### ISSUE TITLE
Netphotographics 2.0

### ISSUE THREAD

**Issue by By-oussef** [sbillard/ZenPhoto20-DEV#21]
Hi @sbillard  I saw that zenphoto work on a version 2.0 is what Netphotographics will have a version 2.0 soon with major improvements.
Thank you

**Comment by sbillard** [comment]
Do you believe this? If you look at the history you will see that they have been promising this for at least three years with no projected completion dnate. Compound that with the fact that there is no branch or other indication of such work on GitHub and you must be skeptical that such a release exists. 

As to npg, what new features are needed? As I have said before you can preview the development of npg by installing the dev release. The version number can go to 2.0 whenever needed. Probability when the current work is done.

**Comment by ghost** [comment]
it's true it's not wrong.
