### ISSUE TITLE
netPhotoGraphics/netPhotoGraphics

### ISSUE THREAD

**Issue by ghost** [sbillard/ZenPhoto20-DEV#22]
Hi @sbillard I created a github repository for netphotographics by deleting zenphoto20 and replacing it with netphotographics. As this users do not confrond with zenphoto and zenphoto20.
I am added as a collaborator you are authorized to modify the content

https://github.com/netPhotoGraphics/netPhotoGraphics
because currently when users are visiting zenphoto20 they are leaving for zenphoto and NPG is losing a lot of users.

netPhotoGraphics/netPhotoGraphics

ZenPhoto20/netPhotoGraphics

**Comment by sbillard** [comment]
This was a really bad thing to do. Do you not think I had considered this? This repository cannot support the current user base. And by creating it you have prevented the current repository from ever migrating to this name.

Remove it immediately and do not ever take this kind of action unilaterally.

**Comment by By-oussef** [comment]
Sorry @sbillard  I do not think you would disagree. I will make it private.

**Comment by sbillard** [comment]
You MUST remove it! If the organization exists then it is not possible to migrate the Zenphoto20 organization to it. That is the plan but takes long term preparation to prevent breaking our user sites. Just existing right now may have already caused damage.

**Comment by By-oussef** [comment]
Hello @sbillard  is what will be implemented in this month ?

**Comment by sbillard** [comment]
The name of the organization will change from zenphoto20 to netPhotoGraphics but It will have to wait a little until our users have had a chance to be up and running on version 2.0.

**Comment by By-oussef** [comment]
Do you have statistical data on the number of users using this version ?

**Comment by sbillard** [comment]
No, that would be a violation of their privacy
