### ISSUE TITLE
Language String Bug?

### ISSUE THREAD

**Issue by wintstar** [sbillard/ZenPhoto20-DEV#24]
zp-core/exif/makers/canon.php:88
https://github.com/sbillard/netPhotoGraphics-DEV/blob/master/zp-core/exif/makers/canon.php#L111

`default: $result['SelfTimer'] .= "/10s";`

?That should not be?
`default: $result['SelfTimer'] .= '!10s!';`

exifTranslations.php line 24
`case '!10s!' : return str_replace($sw, gettext("10s"), $source);`

**Comment by sbillard** [comment]
I am travelling at this time. I'll look at the code when I get back. Do you happen to know how Canon represents its timer values?

**Comment by wintstar** [comment]
No, but maybe here
https://sno.phy.queensu.ca/~phil/exiftool/TagNames/Canon.html

**Comment by sbillard** [comment]
I think you are correct. I will change it.

**Comment by wintstar** [comment]
please look here too => netPhotoGraphics

https://github.com/ZenPhoto20/netPhotoGraphics/blob/master/zp-core/exif/makers/canon.php#L111

I thought that you also look there

**Comment by sbillard** [comment]
This will automatically get updated when I push the development code. In the mean time, feel free to change your copy.

**Comment by sbillard** [comment]
I have done some more research. The timer value is supposed to be the number of tenths of a second that the timer is set to. So the correct change is `default: $result['SelfTimer'] .= '!/10s!';` and the translation should be `case '!/10s!' : return str_replace($sw, gettext("/10s"), $source);`
