### ISSUE TITLE
ZPSkeleton - bad startslideshow link title

### ISSUE THREAD

**Issue by Mates-K1** [sbillard/ZenPhoto20-DEV#3]
![nepojmenovany 1](https://user-images.githubusercontent.com/7648991/39893724-fb61c310-54a4-11e8-9b43-bada007a42b1.jpg)

**Comment by sbillard** [comment]
Thanks for these. If you can, will you check these issues against the base (not DEV) release to see if they are new to the DEV builds?

**Comment by Mates-K1** [comment]
Ok, sorry.

This is not new in latest DEV.

**Comment by sbillard** [comment]
When you click on the button does the slideshow play? It does for me. The link shown when you hoover on the button seems to be a "red herring", an artifact of how the slideshow2 plugin is implemented.

**Comment by Mates-K1** [comment]
Slideshow does not play, it only shows same-sized img in the same browser tab.

List of allowed plugins is in another (#5) DEV issue which I posted today. So slideshow2 is enabled.

M. 
Odesláno z telefonu s Windows 10

Od: Stephen
Odesláno:čtvrtek 10. května 2018 23:51
Komu: sbillard/ZenPhoto20-DEV
Kopie: MartinKroul; Author
Předmět: Re: [sbillard/ZenPhoto20-DEV] ZPSkeleton - bad startslideshow linktitle (#3)

When you click on the button does the slideshow play? It does for me. The link shown when you hoover on the button seems to be a "red herring", an artifact of how the slideshow2 plugin is implemented.

**Comment by sbillard** [comment]
Does the #6 fix resolve this issue? If not then I cannot reproduce it.

**Comment by Mates-K1** [comment]
Still not works for me.

Why there is a link in this button hover tittle? (line 188 in functions.php)

`title="&lt;a href='<?php echo $imagedetaillink; ?>'&gt;<?php echo html_encode(strip_tags($imgobj->getTitle())) . ' (' . gettext('Click for Detail Page') . ')'; ?>&lt;/a&gt;"`

**Comment by sbillard** [comment]
I really do not know why that is there, but it is not really a link. It really does not make any sense, though, so I will change it to be "Slideshow".

Anyway, still works for me, so something else is going on. Can you do two things. Enable the developer console in your browser and see if there are any javascript errors reported. Also in the ZenPHoto20 debug plugin check the "jQuery migration (theme)" "debug" choice and see if this makes a difference. If it does the debug console will likely give us a hint at what script is having a problem. Must be one I do not have enabled.

**Comment by sbillard** [comment]
I did think of another thing to do. Sometimes browsers will not reload scripts they think they already have a copy of. Clear your browser cache so that it has to reload the scripts. Maybe the fixed script is not getting loaded.

**Comment by Mates-K1** [comment]
Latest zpSkeleton (about 3 hours ago)
Title is OK now.

Error from console after image page load:
```
plugin.min.js:1 Uncaught TypeError: Cannot read property 'replace' of undefined
    at YC.<anonymous> (plugin.min.js:1)
    at zm.c.fire (tinymce.min.js:2)
    at YC.fire (tinymce.min.js:2)
    at zC (tinymce.min.js:2)
    at YC.setContent (tinymce.min.js:2)
    at YC.<anonymous> (tinymce.min.js:2)
    at zm.c.fire (tinymce.min.js:2)
    at YC.fire (tinymce.min.js:2)
    at Object.AC.t.formEventDelegate (tinymce.min.js:2)
    at C (tinymce.min.js:2)
    at HTMLFormElement.d (tinymce.min.js:2)
    at Object.trigger (jquery-3.3.1.js:2)
    at HTMLFormElement.<anonymous> (jquery-3.3.1.js:2)
    at Function.each (jquery-3.3.1.js:2)
    at w.fn.init.each (jquery-3.3.1.js:2)
    at w.fn.init.trigger (jquery-3.3.1.js:2)
    at YC.<anonymous> (index.php?album=brigady/pokusne-album&image=002.jpeg:101)
    at zm.c.fire (tinymce.min.js:2)
    at YC.fire (tinymce.min.js:2)
    at pC (tinymce.min.js:2)
    at vC (tinymce.min.js:2)
    at EC (tinymce.min.js:2)
    at YC.<anonymous> (tinymce.min.js:2)
    at Array.<anonymous> (tinymce.min.js:2)
    at At (tinymce.min.js:2)
    at s (tinymce.min.js:2)
    at n (tinymce.min.js:2)
    at HTMLScriptElement.u (tinymce.min.js:2)
```

After clicking slideschow button and returning to img page:
```
jquery-3.3.1.js:2 Uncaught Error: Syntax error, unrecognized expression: #slideshow[group]/3/
    at Function.oe.error (jquery-3.3.1.js:2)
    at oe.tokenize (jquery-3.3.1.js:2)
    at oe.select (jquery-3.3.1.js:2)
    at Function.oe [as find] (jquery-3.3.1.js:2)
    at w.fn.init.find (jquery-3.3.1.js:2)
    at new w.fn.init (jquery-3.3.1.js:2)
    at w (jquery-3.3.1.js:2)
    at index.php?album=brigady/pokusne-album&image=004.jpeg:59
oe.error @ jquery-3.3.1.js:2
oe.tokenize @ jquery-3.3.1.js:2
oe.select @ jquery-3.3.1.js:2
oe @ jquery-3.3.1.js:2
find @ jquery-3.3.1.js:2
w.fn.init @ jquery-3.3.1.js:2
w @ jquery-3.3.1.js:2
(anonymous) @ index.php?album=brigady/pokusne-album&image=004.jpeg:59
load (async)
(anonymous) @ index.php?album=brigady/pokusne-album&image=004.jpeg:58
```

**Comment by sbillard** [comment]
I can see both the errors you get if I enable tinyMCE for comment editing. But still, the slideshow DOES work for me. (Interestingly, the line numbers are different, but the errors are the same.) Anyway, these errors appear with jQuery 11.12 as well, so are unlikely to be involved with the slideshow not working.

The next DEV update will have the option to revert to jQuery 1.12. When that is available you can see it the slideshow works with the older jQuery.

Otherwise I am out of thoughts. No console errors, the show works for me but not for you. But given the experience with Libratus there seem to be incompatibilities that do not show as errors.

**Comment by Mates-K1** [comment]
I apologize for the misunderstanding and my mistake. As I wrote title is OK now... but I forgot to write that the presentation WORKS too. 🥇

**Comment by sbillard** [comment]
Good news.
