### ISSUE TITLE
Gray Highlights - missing img

### ISSUE THREAD

**Issue by Mates-K1** [sbillard/ZenPhoto20-DEV#4]
![b4b994c5-5b53-4945-8136-5601543fc142](https://user-images.githubusercontent.com/7648991/39893847-5d20b8f4-54a5-11e8-8418-d24d77024b41.jpg)

**Comment by Mates-K1** [comment]
New in DEV.

**Comment by sbillard** [comment]
I am not able to reproduce this. Anyway, please inspect the image element. The theme is using an image from the WEB: http://i.creativecommons.org/l/by-sa/3.0/88x31.png So maybe that image is being blocked somehow on your testing.

**Comment by Mates-K1** [comment]
I dont know how, but in DEV_5 it works...
